sdkPath: .fvm/flutter_sdk

name: flutter_inherited_provider_riverpod_comparison

packages:
  - packages/**

scripts:
  lint:all:
    run: melos run analyze && melos run format
  analyze:
    run: dart analyze .

  format:
    run: dart format .
