name: flutter_inherited_provider_riverpod_comparison
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  pedantic_mono: ^1.20.1
