// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwoYM_0WwQUfawWDikFzEovXpMEYAErOM',
    appId: '1:295118838785:web:4b3f81181875b9a582f400',
    messagingSenderId: '295118838785',
    projectId: 'inherited-provider-riverpod',
    authDomain: 'inherited-provider-riverpod.firebaseapp.com',
    storageBucket: 'inherited-provider-riverpod.appspot.com',
    measurementId: 'G-WW4B0FL4Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_sML1DIB82rp7bhcNE4Ar6fbQuk-0rvQ',
    appId: '1:295118838785:android:9ad4f8563184e0a182f400',
    messagingSenderId: '295118838785',
    projectId: 'inherited-provider-riverpod',
    storageBucket: 'inherited-provider-riverpod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM0_m3gDC8MGMLeEiOMYgRXKZbbE9O4RM',
    appId: '1:295118838785:ios:fbbd6868e1faf9e682f400',
    messagingSenderId: '295118838785',
    projectId: 'inherited-provider-riverpod',
    storageBucket: 'inherited-provider-riverpod.appspot.com',
    iosClientId: '295118838785-2bui2gfkur1hnngmoe5hefp9evhjg93i.apps.googleusercontent.com',
    iosBundleId: 'com.kosukesaigusa.inherited',
  );
}
