name: provider_example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.3.0
  common:
    path: ../common
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  flutter:
    sdk: flutter
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  pedantic_mono: ^1.20.1

flutter:
  uses-material-design: true
